AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: discord-skins-bot/workers cloudformation
Parameters:
  TS:
    Type: String
    Description: Build/deploy timestamp passed from GitHub Actions

Resources:
  SkinsbotWorkersRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 'LambdaLoggingPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/skinsbot.tracked_skins'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/skinsbot.guild_info'
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/skinsbot.skin_prices'
  SkinsbotWorkersProducerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: skinsbot-workers-producer
      CodeUri: !Sub 's3://rogerbif-projects/skinsbot/workers_${TS}.zip'
      Description: ''
      MemorySize: 128
      Timeout: 30
      Handler: producer.handler
      Runtime: python3.14
      Architectures:
        - x86_64
      PackageType: Zip
      Role: !GetAtt SkinsbotWorkersRole.Arn

  SkinsbotWorkersConsumerLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: skinsbot-workers-consumer
      CodeUri: !Sub 's3://rogerbif-projects/skinsbot/workers_${TS}.zip'
      Description: ''
      MemorySize: 128
      Timeout: 30
      Handler: consumer.handler
      Runtime: python3.14
      Architectures:
        - x86_64
      PackageType: Zip
      Role: !GetAtt SkinsbotWorkersRole.Arn
  
  WorkersStepFunctions:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: skinsbot-workers-stepfunctions
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource:
                - !GetAtt SkinsbotWorkersProducerLambda.Arn
                - !GetAtt SkinsbotWorkersConsumerLambda.Arn
      Events:
        SkinsbotWorkersCron:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: 'cron(0 18 * * ? *)'
            Input: "{}"
      Definition:
        Comment: State machine definition
        StartAt: SkinsbotWorkersProducerState
        States:
          SkinsbotWorkersProducerState:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Output: '{% $states.result.Payload %}'
            Arguments:
              FunctionName: !GetAtt SkinsbotWorkersProducerLambda.Arn
              Payload: '{% $states.input %}'
            Retry:
              - ErrorEquals:
                  - Lambda.ServiceException
                  - Lambda.AWSLambdaException
                  - Lambda.SdkClientException
                  - Lambda.TooManyRequestsException
                IntervalSeconds: 1
                MaxAttempts: 3
                BackoffRate: 2
                JitterStrategy: FULL
            Next: Map
          Map:
            Type: Map
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: SkinsbotWorkersConsumerState
              States:
                SkinsbotWorkersConsumerState:
                  Type: Task
                  Resource: arn:aws:states:::lambda:invoke
                  Output: '{% $states.result.Payload %}'
                  Arguments:
                    FunctionName: !GetAtt SkinsbotWorkersConsumerLambda.Arn
                    Payload: '{% $states.input %}'
                  Retry:
                    - ErrorEquals:
                        - Lambda.ServiceException
                        - Lambda.AWSLambdaException
                        - Lambda.SdkClientException
                        - Lambda.TooManyRequestsException
                      IntervalSeconds: 1
                      MaxAttempts: 3
                      BackoffRate: 2
                      JitterStrategy: FULL
                  Next: Wait
                  Catch:
                    - ErrorEquals:
                        - States.ALL
                      Next: Wait
                      Comment: Ignore error
                Wait:
                  Type: Wait
                  Seconds: 5
                  End: true
            End: true
            MaxConcurrency: 1
        QueryLanguage: JSONata
      
